/* Generated Code */

#include "thxdef.h"
#include <stdio.h>
#define FILE struct _iobuf
void  CppFBP(label_ent * label_blk, bool dynam,  FILE * fp, bool timereq);
THRCOMP SendString(anchor anch);
proc_ent P0 = {0, "SendRepoKey", "strings/SendString", SendString, 0, 0, !TRACE,  !COMPOS};
THRCOMP GetObjectKey(anchor anch);
proc_ent P1 = {&P0, "GetRepoToPrepare", "objects/GetObjectKey", GetObjectKey, 0, 0, !TRACE,  !COMPOS};
THRCOMP Split(anchor anch);
proc_ent P2 = {&P1, "RepoToPrepare", "core/Split", Split, 0, 0, !TRACE,  !COMPOS};
THRCOMP Repeat(anchor anch);
proc_ent P3 = {&P2, "Token", "core/Repeat", Repeat, 0, 0, !TRACE,  !COMPOS};
THRCOMP GetReference(anchor anch);
proc_ent P4 = {&P3, "GetReference", "github/GetReference", GetReference, 0, 0, !TRACE,  !COMPOS};
THRCOMP CheckSyncState(anchor anch);
proc_ent P5 = {&P4, "CheckSyncState", "ui/CheckSyncState", CheckSyncState, 0, 0, !TRACE,  !COMPOS};
proc_ent P6 = {&P5, "SendProjectKey", "strings/SendString", SendString, 0, 0, !TRACE,  !COMPOS};
proc_ent P7 = {&P6, "GetProject", "objects/GetObjectKey", GetObjectKey, 0, 0, !TRACE,  !COMPOS};
THRCOMP Merge(anchor anch);
proc_ent P8 = {&P7, "Errors", "core/Merge", Merge, 0, 0, !TRACE,  !COMPOS};
proc_ent P9 = {&P8, "MergeOps", "core/Merge", Merge, 0, 0, !TRACE,  !COMPOS};
proc_ent P10 = {&P9, "DoSync", "core/Repeat", Repeat, 0, 0, !TRACE,  !COMPOS};
THRCOMP PreparePulls(anchor anch);
proc_ent P11 = {&P10, "PreparePulls", "ui/PreparePulls", PreparePulls, 0, 0, !TRACE,  !COMPOS};
THRCOMP GetBlob(anchor anch);
proc_ent P12 = {&P11, "GetBlob", "github/GetBlob", GetBlob, 0, 0, !TRACE,  !COMPOS};
THRCOMP BlobToEntry(anchor anch);
proc_ent P13 = {&P12, "BlobToEntry", "ui/BlobToEntry", BlobToEntry, 0, 0, !TRACE,  !COMPOS};
THRCOMP Race(anchor anch);
proc_ent P14 = {&P13, "CompletePulls", "flow/Race", Race, 0, 0, !TRACE,  !COMPOS};
proc_ent P15 = {&P14, "UpdatedComponent", "core/Merge", Merge, 0, 0, !TRACE,  !COMPOS};
proc_ent P16 = {&P15, "UpdatedGraph", "core/Merge", Merge, 0, 0, !TRACE,  !COMPOS};
proc_ent P17 = {&P16, "UpdatedSpec", "core/Merge", Merge, 0, 0, !TRACE,  !COMPOS};
proc_ent P18 = {&P17, "Ready", "core/Repeat", Repeat, 0, 0, !TRACE,  !COMPOS};
THRCOMP PreparePush(anchor anch);
proc_ent P19 = {&P18, "PreparePush", "ui/PreparePush", PreparePush, 0, 0, !TRACE,  !COMPOS};
THRCOMP UpdateFromTree(anchor anch);
proc_ent P20 = {&P19, "UpdateFromTree", "ui/UpdateFromTree", UpdateFromTree, 0, 0, !TRACE,  !COMPOS};
THRCOMP CreateTree(anchor anch);
proc_ent P21 = {&P20, "CreateTree", "github/CreateTree", CreateTree, 0, 0, !TRACE,  !COMPOS};
proc_ent P22 = {&P21, "SendTreeSha", "strings/SendString", SendString, 0, 0, !TRACE,  !COMPOS};
proc_ent P23 = {&P22, "GetTreeSha", "objects/GetObjectKey", GetObjectKey, 0, 0, !TRACE,  !COMPOS};
THRCOMP CreateCommit(anchor anch);
proc_ent P24 = {&P23, "CreateCommit", "github/CreateCommit", CreateCommit, 0, 0, !TRACE,  !COMPOS};
THRCOMP UpdateReference(anchor anch);
proc_ent P25 = {&P24, "UpdateReference", "github/UpdateReference", UpdateReference, 0, 0, !TRACE,  !COMPOS};
proc_ent P26 = {&P25, "SendPullRepo", "strings/SendString", SendString, 0, 0, !TRACE,  !COMPOS};
proc_ent P27 = {&P26, "GetPullRepo", "objects/GetObjectKey", GetObjectKey, 0, 0, !TRACE,  !COMPOS};
proc_ent P28 = {&P27, "PullRepo", "core/Split", Split, 0, 0, !TRACE,  !COMPOS};
proc_ent P29 = {&P28, "Loading", "core/Repeat", Repeat, 0, 0, !TRACE,  !COMPOS};
proc_ent P30 = {&P29, "GetPullReference", "github/GetReference", GetReference, 0, 0, !TRACE,  !COMPOS};
proc_ent P31 = {&P30, "CheckPullState", "ui/CheckSyncState", CheckSyncState, 0, 0, !TRACE,  !COMPOS};
proc_ent P32 = {&P31, "SendPullProject", "strings/SendString", SendString, 0, 0, !TRACE,  !COMPOS};
proc_ent P33 = {&P32, "GetPullProject", "objects/GetObjectKey", GetObjectKey, 0, 0, !TRACE,  !COMPOS};
THRCOMP (anchor anch);
proc_ent P34 = {&P33, "", "", , 0, 0, !TRACE,  !COMPOS};
IIP I0 = {"repo"};
cnxt_ent C0 = {0, "!", " ", 0, "SendRepoKey", "STRING", 0, &I0, 0};
cnxt_ent C1 = {&C0, "SendRepoKey", "OUT", 0, "GetRepoToPrepare", "KEY", 0, 0, 6};
cnxt_ent C2 = {&C1, "RepoToPrepare", "OUT", 0, "GetRepoToPrepare", "IN", 0, 0, 6};
cnxt_ent C3 = {&C2, "RepoToPrepare", "OUT", 0, "SendRepoKey", "IN", 0, 0, 6};
cnxt_ent C4 = {&C3, "Token", "OUT", 0, "GetReference", "TOKEN", 0, 0, 6};
cnxt_ent C5 = {&C4, "GetRepoToPrepare", "OUT", 0, "GetReference", "REPOSITORY", 0, 0, 6};
cnxt_ent C6 = {&C5, "GetReference", "REFERENCE", 0, "CheckSyncState", "REFERENCE", 0, 0, 6};
IIP I1 = {"project"};
cnxt_ent C7 = {&C6, "!", " ", 0, "SendProjectKey", "STRING", 0, &I1, 0};
cnxt_ent C8 = {&C7, "SendProjectKey", "OUT", 0, "GetProject", "KEY", 0, 0, 6};
cnxt_ent C9 = {&C8, "GetRepoToPrepare", "OBJECT", 0, "GetProject", "IN", 0, 0, 6};
cnxt_ent C10 = {&C9, "GetProject", "OUT", 0, "CheckSyncState", "PROJECT", 0, 0, 6};
cnxt_ent C11 = {&C10, "GetRepoToPrepare", "OBJECT", 0, "SendProjectKey", "IN", 0, 0, 6};
cnxt_ent C12 = {&C11, "Token", "OUT", 0, "CheckSyncState", "TOKEN", 0, 0, 6};
cnxt_ent C13 = {&C12, "GetReference", "ERROR", 0, "Errors", "IN", 0, 0, 6};
cnxt_ent C14 = {&C13, "CheckSyncState", "ERROR", 0, "Errors", "IN", 0, 0, 6};
cnxt_ent C15 = {&C14, "CheckSyncState", "NOOP", 0, "MergeOps", "IN", 0, 0, 6};
cnxt_ent C16 = {&C15, "CheckSyncState", "LOCAL", 0, "MergeOps", "IN", 0, 0, 6};
cnxt_ent C17 = {&C16, "CheckSyncState", "REMOTE", 0, "MergeOps", "IN", 0, 0, 6};
cnxt_ent C18 = {&C17, "CheckSyncState", "BOTH", 0, "MergeOps", "IN", 0, 0, 6};
cnxt_ent C19 = {&C18, "DoSync", "OUT", 0, "PreparePulls", "IN", 0, 0, 6};
cnxt_ent C20 = {&C19, "Token", "OUT", 0, "GetBlob", "TOKEN", 0, 0, 6};
cnxt_ent C21 = {&C20, "PreparePulls", "OUT", 0, "BlobToEntry", "OPERATION", 0, 0, 6};
cnxt_ent C22 = {&C21, "PreparePulls", "REPOSITORY", 0, "GetBlob", "REPOSITORY", 0, 0, 6};
cnxt_ent C23 = {&C22, "PreparePulls", "SHA", 0, "GetBlob", "SHA", 0, 0, 6};
cnxt_ent C24 = {&C23, "GetBlob", "OUT", 0, "CompletePulls", "IN", 0, 0, 6};
cnxt_ent C25 = {&C24, "CompletePulls", "OUT", 0, "BlobToEntry", "BLOB", 0, 0, 6};
cnxt_ent C26 = {&C25, "GetBlob", "ERROR", 0, "CompletePulls", "ERROR", 0, 0, 6};
cnxt_ent C27 = {&C26, "CompletePulls", "ERROR", 0, "Errors", "IN", 0, 0, 6};
cnxt_ent C28 = {&C27, "BlobToEntry", "COMPONENT", 0, "UpdatedComponent", "IN", 0, 0, 6};
cnxt_ent C29 = {&C28, "BlobToEntry", "GRAPH", 0, "UpdatedGraph", "IN", 0, 0, 6};
cnxt_ent C30 = {&C29, "BlobToEntry", "SPEC", 0, "UpdatedSpec", "IN", 0, 0, 6};
cnxt_ent C31 = {&C30, "BlobToEntry", "PROJECT", 0, "Ready", "IN", 0, 0, 6};
cnxt_ent C32 = {&C31, "BlobToEntry", "ERROR", 0, "Errors", "IN", 0, 0, 6};
cnxt_ent C33 = {&C32, "DoSync", "OUT", 0, "PreparePush", "IN", 0, 0, 6};
cnxt_ent C34 = {&C33, "PreparePush", "OUT", 0, "UpdateFromTree", "IN", 0, 0, 6};
cnxt_ent C35 = {&C34, "PreparePush", "BASETREE", 0, "CreateTree", "BASE", 0, 0, 6};
cnxt_ent C36 = {&C35, "Token", "OUT", 0, "CreateTree", "TOKEN", 0, 0, 6};
cnxt_ent C37 = {&C36, "PreparePush", "TREE", 0, "CreateTree", "TREE", 0, 0, 6};
cnxt_ent C38 = {&C37, "PreparePush", "REPOSITORY", 0, "CreateTree", "REPOSITORY", 0, 0, 6};
cnxt_ent C39 = {&C38, "CreateTree", "OUT", 0, "UpdateFromTree", "TREE", 0, 0, 6};
cnxt_ent C40 = {&C39, "PreparePush", "REPOSITORY", 0, "UpdateFromTree", "REPOSITORY", 0, 0, 6};
cnxt_ent C41 = {&C40, "Token", "OUT", 0, "UpdateFromTree", "TOKEN", 0, 0, 6};
IIP I2 = {"sha"};
cnxt_ent C42 = {&C41, "!", " ", 0, "SendTreeSha", "STRING", 0, &I2, 0};
cnxt_ent C43 = {&C42, "SendTreeSha", "OUT", 0, "GetTreeSha", "KEY", 0, 0, 6};
cnxt_ent C44 = {&C43, "CreateTree", "OUT", 0, "GetTreeSha", "IN", 0, 0, 6};
cnxt_ent C45 = {&C44, "CreateTree", "OUT", 0, "SendTreeSha", "IN", 0, 0, 6};
cnxt_ent C46 = {&C45, "GetTreeSha", "OUT", 0, "CreateCommit", "TREE", 0, 0, 6};
cnxt_ent C47 = {&C46, "Token", "OUT", 0, "CreateCommit", "TOKEN", 0, 0, 6};
cnxt_ent C48 = {&C47, "PreparePush", "MESSAGE", 0, "CreateCommit", "MESSAGE", 0, 0, 6};
cnxt_ent C49 = {&C48, "PreparePush", "PARENTCOMMITS", 0, "CreateCommit", "PARENTS", 0, 0, 6};
cnxt_ent C50 = {&C49, "PreparePush", "REPOSITORY", 0, "CreateCommit", "REPOSITORY", 0, 0, 6};
cnxt_ent C51 = {&C50, "CreateCommit", "OUT", 0, "UpdateReference", "COMMIT", 0, 0, 6};
cnxt_ent C52 = {&C51, "PreparePush", "REF", 0, "UpdateReference", "REFERENCE", 0, 0, 6};
cnxt_ent C53 = {&C52, "Token", "OUT", 0, "UpdateReference", "TOKEN", 0, 0, 6};
cnxt_ent C54 = {&C53, "PreparePush", "REPOSITORY", 0, "UpdateReference", "REPOSITORY", 0, 0, 6};
cnxt_ent C55 = {&C54, "UpdateFromTree", "COMPONENT", 0, "UpdatedComponent", "IN", 0, 0, 6};
cnxt_ent C56 = {&C55, "UpdateFromTree", "GRAPH", 0, "UpdatedGraph", "IN", 0, 0, 6};
cnxt_ent C57 = {&C56, "UpdateFromTree", "SPEC", 0, "UpdatedSpec", "IN", 0, 0, 6};
cnxt_ent C58 = {&C57, "UpdateFromTree", "ERROR", 0, "Errors", "IN", 0, 0, 6};
cnxt_ent C59 = {&C58, "CreateTree", "ERROR", 0, "Errors", "IN", 0, 0, 6};
cnxt_ent C60 = {&C59, "CreateCommit", "ERROR", 0, "Errors", "IN", 0, 0, 6};
cnxt_ent C61 = {&C60, "UpdateReference", "ERROR", 0, "Errors", "IN", 0, 0, 6};
IIP I3 = {"repo"};
cnxt_ent C62 = {&C61, "!", " ", 0, "SendPullRepo", "STRING", 0, &I3, 0};
cnxt_ent C63 = {&C62, "SendPullRepo", "OUT", 0, "GetPullRepo", "KEY", 0, 0, 6};
cnxt_ent C64 = {&C63, "PullRepo", "OUT", 0, "Loading", "IN", 0, 0, 6};
cnxt_ent C65 = {&C64, "PullRepo", "OUT", 0, "GetPullRepo", "IN", 0, 0, 6};
cnxt_ent C66 = {&C65, "PullRepo", "OUT", 0, "SendPullRepo", "IN", 0, 0, 6};
cnxt_ent C67 = {&C66, "Token", "OUT", 0, "GetPullReference", "TOKEN", 0, 0, 6};
cnxt_ent C68 = {&C67, "GetPullRepo", "OUT", 0, "GetPullReference", "REPOSITORY", 0, 0, 6};
cnxt_ent C69 = {&C68, "GetPullReference", "REFERENCE", 0, "CheckPullState", "REFERENCE", 0, 0, 6};
IIP I4 = {"project"};
cnxt_ent C70 = {&C69, "!", " ", 0, "SendPullProject", "STRING", 0, &I4, 0};
cnxt_ent C71 = {&C70, "SendPullProject", "OUT", 0, "GetPullProject", "KEY", 0, 0, 6};
cnxt_ent C72 = {&C71, "GetPullRepo", "OBJECT", 0, "GetPullProject", "IN", 0, 0, 6};
cnxt_ent C73 = {&C72, "GetPullProject", "OUT", 0, "CheckPullState", "PROJECT", 0, 0, 6};
cnxt_ent C74 = {&C73, "GetPullRepo", "OBJECT", 0, "SendPullProject", "IN", 0, 0, 6};
cnxt_ent C75 = {&C74, "Token", "OUT", 0, "CheckPullState", "TOKEN", 0, 0, 6};
cnxt_ent C76 = {&C75, "GetPullReference", "ERROR", 0, "Errors", "IN", 0, 0, 6};
cnxt_ent C77 = {&C76, "CheckPullState", "REMOTE", 0, "DoSync", "IN", 0, 0, 6};
cnxt_ent C78 = {&C77, "CheckPullState", "ERROR", 0, "Errors", "IN", 0, 0, 6};
label_ent LABELTAB = {0, " ", "", &C78, &P34, 'L'};
void main() {
CppFBP(&LABELTAB, 0, 0, 0);
}
